steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/my-repository/sample-app:v1.0'

- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials hello-cluster --zone=us-west1-c &&
    kubectl apply -f dev/deployment.yaml --namespace=dev

options:
  logging: CLOUD_LOGGING_ONLY
